# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HPGPUImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HPGPUImage

  target 'HPGPUImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HPGPUImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
